version: '3.5'
services:
  zookeepeTest:
    image: wurstmeister/zookeeper
    container_name: zookeeperTest
    ports:
      - "2181:2181"                 ## 对外暴露的端口号
  kafkaTest:
    image: wurstmeister/kafka       ## 镜像
    container_name: kafkaTest
    volumes:
      - /etc/localtime:/etc/localtime ## 挂载位置
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 123.57.212.188                   ## 修改:宿主机IP
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://123.57.212.188:9092    ## 修改:宿主机IP
      KAFKA_ZOOKEEPER_CONNECT: "zookeeperTest:2181"
      KAFKA_ADVERTISED_PORT: 9092
  kafka-uiTest:
    image: provectuslabs/kafka-ui
    container_name: kafka-uiTest
    ports:
      - "8888:8080"
    depends_on:
      - kafkaTest
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: Test
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: kafkaTest:9092  # 使用 Kafka 服务的内部网络地址
